<?php
//Custom Layouts
$layouts = array(
		'footer_354' => array(
				'name' => 'Footer',
				'template' => '[vc_row scheme=\"dark\" row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\"][vc_column icons_position=\"left\"][vc_empty_space alter_height=\"medium\" hide_on_mobile=\"\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\"][vc_row_inner row_delimiter=\"\"][vc_column_inner width=\"1/3\" icons_position=\"left\"][trx_widget_contacts googlemap=\"\" socials=\"\" logo=\"355\" description=\"Omnis iste natus sit voluptatem accusanti dolorem laudantium totam rem aperiam.\" address=\"123, New Lenox, Chicago, IL 60606\" phone=\"1 (800) 123-4567\" email=\"info@yoursite.com\"][/trx_widget_contacts][/vc_column_inner][vc_column_inner width=\"1/3\" icons_position=\"left\"][trx_widget_recent_posts number=\"2\" show_counters=\"\" show_categories=\"\" title=\"Recent Posts\"][/vc_column_inner][vc_column_inner width=\"1/3\" icons_position=\"left\"][vc_column_text el_class=\"widget\"]
<h5 class=\"widget_title\">Newsletter</h5>
[mc4wp_form id=\"398\"][/vc_column_text][/vc_column_inner][/vc_row_inner][/trx_sc_content][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\"][/vc_column][/vc_row][vc_row full_width=\"stretch_row_content_no_spaces\" scheme=\"dark\" row_type=\"compact\" row_delimiter=\"\" row_fixed=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" el_class=\"footer_copyright_inner\"][vc_column icons_position=\"left\"][trx_sc_content size=\"1_1\" float=\"center\" number_position=\"br\" title_style=\"default\"][vc_row_inner][vc_column_inner el_class=\"w800_100p\" width=\"1/2\" column_align=\"left\" icons_position=\"left\"][vc_wp_text]<a href=\"http://themeforest.net/user/axiomthemes/portfolio\" target=\"_blank\" rel=\"noopener noreferrer\">AxiomThemes</a> &copy; {Y} All rights reserved. <a href=\"http://axiomthemes.com/terms-of-service/\" target=\"_blank\" rel=\"noopener noreferrer\">Terms of use</a> and <a href=\"/privacy-policy/\" rel=\"noopener noreferrer\">Privacy Policy</a>[/vc_wp_text][/vc_column_inner][vc_column_inner el_class=\"w800_100p\" width=\"1/2\" column_align=\"right\" icons_position=\"right\"][trx_widget_socials align=\"right\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'footer'
								)
						)
				),
		'footer_581' => array(
				'name' => 'Footer with insta',
				'template' => '[vc_row scheme=\"dark\" row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\"][vc_column icons_position=\"left\"][vc_empty_space alter_height=\"medium\" hide_on_mobile=\"\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\"][vc_row_inner row_delimiter=\"\"][vc_column_inner width=\"1/3\" icons_position=\"left\"][trx_widget_contacts googlemap=\"\" socials=\"\" logo=\"355\" description=\"Omnis iste natus sit voluptatem accusanti dolorem laudantium totam rem aperiam.\" address=\"123, New Lenox, Chicago, IL 60606\" phone=\"1 (800) 123-4567\" email=\"info@yoursite.com\"][/trx_widget_contacts][/vc_column_inner][vc_column_inner width=\"1/3\" icons_position=\"left\"][trx_widget_recent_posts number=\"2\" show_counters=\"\" show_categories=\"\" title=\"Recent Posts\"][/vc_column_inner][vc_column_inner width=\"1/3\" icons_position=\"left\"][trx_widget_instagram title=\"Instagram\" demo=\"1\" demo_files=\"%5B%7B%22image%22%3A%221095%22%7D%2C%7B%22image%22%3A%221097%22%7D%2C%7B%22image%22%3A%221094%22%7D%2C%7B%22image%22%3A%221093%22%7D%2C%7B%22image%22%3A%221092%22%7D%2C%7B%22image%22%3A%221096%22%7D%5D\" columns=\"3\" columns_gap=\"10\" links=\"none\" follow=\"\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\"][/vc_column][/vc_row][vc_row full_width=\"stretch_row_content_no_spaces\" scheme=\"dark\" row_type=\"compact\" row_delimiter=\"\" row_fixed=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" el_class=\"footer_copyright_inner\"][vc_column icons_position=\"left\"][trx_sc_content size=\"1_1\" float=\"center\" number_position=\"br\" title_style=\"default\"][vc_row_inner][vc_column_inner el_class=\"w800_100p\" width=\"1/2\" column_align=\"left\" icons_position=\"left\"][vc_wp_text]&lt;a href=\"http://themeforest.net/user/axiomthemes/portfolio\" target=\"_blank\" rel=\"noopener\"&gt;AxiomThemes&lt;/a&gt; &copy; {Y} All rights reserved. &lt;a href=\"http://axiomthemes.com/terms-of-service/\" target=\"_blank\" rel=\"noopener\"&gt;Terms of use&lt;/a&gt; and &lt;a href=\"/privacy-policy/\" rel=\"noopener\"&gt;Privacy Policy&lt;/a&gt;[/vc_wp_text][/vc_column_inner][vc_column_inner el_class=\"w800_100p\" width=\"1/2\" column_align=\"right\" icons_position=\"right\"][trx_widget_socials align=\"right\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'footer'
								)
						)
				),
		'header_20' => array(
				'name' => 'Header Main',
				'template' => '[vc_row scheme=\"dark\" row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" hide_on_frontpage=\"\" el_class=\"header_main_top\"][vc_column width=\"1/2\" column_align=\"left\" icons_position=\"left\" css=\".vc_custom_1487855727189{padding-left: 70px !important;}\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"icon-location-light\" text1=\"28 tenth Avenue Boston, BT 58966\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"icon-envelope\" text1=\"Info@studeon.com\" link=\"mailto:Info@studeon.com\"][/vc_column][vc_column width=\"1/2\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_search style=\"normal\" ajax=\"\"][trx_sc_layouts_login text_login=\"Login / Register\"][/vc_column][/vc_row][vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1487855614213{background-color: #ffffff !important;}\" el_class=\"header_main_middle\"][vc_column width=\"1/4\" column_align=\"left\" icons_position=\"left\" column_type=\"center\"][trx_sc_layouts_logo logo=\"367\" logo_retina=\"368\"][/vc_column][vc_column width=\"3/4\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][trx_sc_layouts_cart][/vc_column][/vc_row][vc_row row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"1\" el_class=\"header_main_bottom top_panel_title\"][vc_column column_align=\"center\" icons_position=\"left\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\"][trx_sc_layouts_title title=\"1\" meta=\"\" breadcrumbs=\"1\" icon_type=\"fontawesome\" icon_fontawesome=\"\"][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1487855614213{background-color: #ffffff !important;}.vc_custom_1487855727189{padding-left: 70px !important;}'
						)
				),
		'header_665' => array(
				'name' => 'Header Main - home 3',
				'template' => '[vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1487855614213{background-color: #ffffff !important;}\" el_class=\"header_main_middle\"][vc_column width=\"1/4\" column_align=\"left\" icons_position=\"left\" column_type=\"center\"][trx_sc_layouts_logo][/vc_column][vc_column width=\"3/4\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][trx_sc_layouts_search style=\"expand\" ajax=\"\" hide_on_tablet=\"1\" hide_on_mobile=\"1\"][trx_sc_layouts_cart][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1487855614213{background-color: #ffffff !important;}'
						)
				),
		'header_582' => array(
				'name' => 'Header Main - no title & breadcrumbs',
				'template' => '[vc_row scheme=\"dark\" row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" hide_on_frontpage=\"\" el_class=\"header_main_top\"][vc_column width=\"1/2\" column_align=\"left\" icons_position=\"left\" css=\".vc_custom_1487855727189{padding-left: 70px !important;}\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"icon-location-light\" text1=\"28 tenth Avenue Boston, BT 58966\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"icon-envelope\" text1=\"Info@studeon.com\" link=\"mailto:Info@studeon.com\"][/vc_column][vc_column width=\"1/2\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_search style=\"normal\" ajax=\"\"][trx_sc_layouts_login text_login=\"Login / Register\"][/vc_column][/vc_row][vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1487855614213{background-color: #ffffff !important;}\" el_class=\"header_main_middle\"][vc_column width=\"1/4\" column_align=\"left\" icons_position=\"left\" column_type=\"center\"][trx_sc_layouts_logo][/vc_column][vc_column width=\"3/4\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][trx_sc_layouts_cart][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1487855614213{background-color: #ffffff !important;}.vc_custom_1487855727189{padding-left: 70px !important;}'
						)
				),
		'header_514' => array(
				'name' => 'Header Main - shop',
				'template' => '[vc_row scheme=\"dark\" row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" hide_on_frontpage=\"\" el_class=\"header_main_top\"][vc_column width=\"1/2\" column_align=\"left\" icons_position=\"left\" css=\".vc_custom_1487855727189{padding-left: 70px !important;}\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"icon-location-light\" text1=\"28 tenth Avenue Boston, BT 58966\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"icon-envelope\" text1=\"Info@studeon.com\" link=\"mailto:Info@studeon.com\"][/vc_column][vc_column width=\"1/2\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_search style=\"normal\" ajax=\"\"][trx_sc_layouts_login text_login=\"Login / Register\"][/vc_column][/vc_row][vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1487855614213{background-color: #ffffff !important;}\" el_class=\"header_main_middle\"][vc_column width=\"1/4\" column_align=\"left\" icons_position=\"left\" column_type=\"center\"][trx_sc_layouts_logo][/vc_column][vc_column width=\"3/4\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][trx_sc_layouts_cart][/vc_column][/vc_row][vc_row row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"1\" el_class=\"header_main_bottom top_panel_title\"][vc_column column_align=\"center\" icons_position=\"left\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\"][vc_custom_heading text=\"Our Shop\" font_container=\"tag:h2|font_size:2.765em|text_align:center|line_height:1.13em\" use_theme_fonts=\"yes\" css=\".vc_custom_1488797331829{margin-top: 0px !important;margin-bottom: 0px !important;padding-top: 7px !important;}\"][trx_sc_layouts_title title=\"\" meta=\"\" breadcrumbs=\"1\" icon_type=\"fontawesome\" icon_fontawesome=\"\"][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1487855614213{background-color: #ffffff !important;}.vc_custom_1487855727189{padding-left: 70px !important;}.vc_custom_1488797331829{margin-top: 0px !important;margin-bottom: 0px !important;padding-top: 7px !important;}'
						)
				),
		'header_713' => array(
				'name' => 'Header Main - transparent',
				'template' => '[vc_row scheme=\"dark\" row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" hide_on_frontpage=\"\" el_class=\"header_main_top\"][vc_column width=\"1/2\" column_align=\"left\" icons_position=\"left\" css=\".vc_custom_1487855727189{padding-left: 70px !important;}\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"icon-location-light\" text1=\"28 tenth Avenue Boston, BT 58966\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"icon-envelope\" link=\"mailto:Info@studeon.com\" text1=\"Info@studeon.com\"][/vc_column][vc_column width=\"1/2\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_search style=\"normal\" ajax=\"\"][trx_sc_layouts_login text_login=\"Login / Register\"][/vc_column][/vc_row][vc_row scheme=\"dark\" row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" el_class=\"header_main_middle transparent_bg\"][vc_column width=\"1/4\" column_align=\"left\" icons_position=\"left\" column_type=\"center\"][trx_sc_layouts_logo logo=\"372\"][/vc_column][vc_column width=\"3/4\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][trx_sc_layouts_cart][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1487855727189{padding-left: 70px !important;}'
						)
				),
		'header_516' => array(
				'name' => 'Header Main - white bg',
				'template' => '[vc_row scheme=\"dark\" row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" hide_on_frontpage=\"\" el_class=\"header_main_top\"][vc_column width=\"1/2\" column_align=\"left\" icons_position=\"left\" css=\".vc_custom_1487855727189{padding-left: 70px !important;}\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"icon-location-light\" text1=\"28 tenth Avenue Boston, BT 58966\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"icon-envelope\" text1=\"Info@studeon.com\" link=\"mailto:Info@studeon.com\"][/vc_column][vc_column width=\"1/2\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_search style=\"normal\" ajax=\"\"][trx_sc_layouts_login text_login=\"Login / Register\"][/vc_column][/vc_row][vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1487855614213{background-color: #ffffff !important;}\" el_class=\"header_main_middle\"][vc_column width=\"1/4\" column_align=\"left\" icons_position=\"left\" column_type=\"center\"][trx_sc_layouts_logo][/vc_column][vc_column width=\"3/4\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][trx_sc_layouts_cart][/vc_column][/vc_row][vc_row row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"1\" el_class=\"header_main_bottom top_panel_title\" css=\".vc_custom_1488807133162{background-color: #ffffff !important;}\"][vc_column column_align=\"center\" icons_position=\"left\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\"][trx_sc_layouts_title title=\"1\" meta=\"\" breadcrumbs=\"1\" icon_type=\"fontawesome\" icon_fontawesome=\"\"][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1487855614213{background-color: #ffffff !important;}.vc_custom_1488807133162{background-color: #ffffff !important;}.vc_custom_1487855727189{padding-left: 70px !important;}'
						)
				)
		);
?>